# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: "ja-JP"
title: &title "yiwkr blog"
title_separator : "-"
subtitle:
name: &name "yiwkr"
email: "iwakiri.yutaro@gmail.com"
description: &description "メモ置き場"
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://yiwkr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "yiwkr/blog"
search: true
search_full_content: true
search_provider: "lunr"
twitter:
  username: "yiwkr"
social:
  type:
  name:
  links:
    - "https://twitter.com/yiwkr"

# Analytics
{% if production %}
analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-163387568-1"
    anoymize_ip: true
{% endif %}

# Site Author
author:
  name: *name
  avatar: "/assets/images/profile.jpg"
  bio:
  location: "神奈川県"
  links:
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/yiwkr"
  - label: "Twitter"
    icon: "fab fa-fw fa-twitter-square"
    url: "https://twitter.com/yiwkr"
  - label: "Email"
    icon: "fas fa-fw fa-envelope-square"
    url: "mailto:iwakiri.yutaro@gmail.com"

# Site Footer
footer:
  links:
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/yiwkr"
  - label: "Twitter"
    icon: "fab fa-fw fa-twitter-square"
    url: "https://twitter.com/yiwkr"

# Build settings
markdown: "kramdown"
{% if production %}
remote_theme: mmistakes/minimal-mistakes@4.19.1
{% else %}
theme: "minimal-mistakes-jekyll"
{% endif %}
minimal_mistakes_skin: "default"
plugins:
  - "jekyll-sitemap"
  - "jekyll-feed"
  - "jemoji"
  - "jekyll-include-cache"

  - "jekyll-coffeescript"
  - "jekyll-default-layout"
  - "jekyll-gist"
  - "jekyll-github-metadata"
  - "jekyll-optional-front-matter"
  - "jekyll-paginate"
  - "jekyll-readme-index"
  - "jekyll-titles-from-headings"
  - "jekyll-relative-links"

whitelist:
  - "jekyll-sitemap"
  - "jekyll-feed"
  - "jemoji"
  - "jekyll-include-cache"

  - "jekyll-coffeescript"
  - "jekyll-default-layout"
  - "jekyll-gist"
  - "jekyll-github-metadata"
  - "jekyll-optional-front-matter"
  - "jekyll-paginate"
  - "jekyll-readme-index"
  - "jekyll-titles-from-headings"
  - "jekyll-relative-links"

include:
  - "_pages"
  - "site.webmanifest"
exclude:
   - "Gemfile"
   - "Gemfile.lock"
   - "node_modules"
   - "vendor/bundle/"
   - "vendor/cache/"
   - "vendor/gems/"
   - "vendor/ruby/"

# Archives
category_archive:
  type: "liquid"
  path: "/categories/"
tag_archive:
  type: "liquid"
  path: "/tags/"

# Comments
comments:
  provider: "utterances"
  utterances:
    theme: "github-light"
    issue_term: "pathname"

# Feed
feed:
  excerpt_only: true

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      permalink: "/:year-:month-:day-:title"
      author_profile: true
      read_time: true
      share: true
      related: true
      toc: true
      toc_sticky: true
      comments: true
  # _pages
  - scope:
      path: "_pages"
      type: "pages"
    values: &defaults_pages_values
      layout: "single"
      author_profile: true
  # _pages/home.md
  - scope:
      path: "_pages/home.md"
      type: "pages"
    values:
      <<: *defaults_pages_values
      permalink: "/"
      layout: "home"
      excerpt: *description
